services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-custom
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n.aliendevelopers.com
      - WEBHOOK_URL=https://n8n.aliendevelopers.com
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_BINARY_DATA_TTL=604800
      - N8N_BINARY_DATA_MAX_SIZE=2048
    volumes:
      - /home/ubuntu/.n8n:/home/node/.n8n

  ffmpeg:
    image: jrottenberg/ffmpeg:6.1-ubuntu
    container_name: ffmpeg
    restart: unless-stopped
    volumes:
      - /home/ubuntu/.n8n:/data
    entrypoint: ["tail", "-f", "/dev/null"]


  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: